#+STARTUP: content
#+CREATED: [2021-06-21 09:27]
* keep-alive

  KeepAlive is an internal component of due, in order to cached all unactive components.  Like v-if etc.

  Root: ~/src/core/components/keep-alive.js~ (124 line only , Jesus🙈)

** props

   Value: components name.

   Type: string, can be one component name or more split by ~,~
   or a regular expression.

   - include
   - exclude

** Implement

*** Create

    When ~created~, ~KeepAlive~ will create a ~cache~ Object and a Array named ~keys~ to save them.

    ~Keys~ saves keys of  ~cache~ to  record the length of cache, to clean some older cache when it is longer than max-length.
    For better performance.

*** Render

    ~KeepAlive~ only care about the first child component in slot.

    When ~render~, ~KeepAlive~ will check all props to decide whether cache the first child component.

    If not, just return the vnode directly.

    Every vnode has its key as a unique id to identify itself.

    If the component need to be cached, ~KeepAlive~ will check if it has be cached by the only key.

    If existed already, just return the old vnode. If not, just cache it.

*** Mounted

    After ~mounted~, ~KeepAlive~ begin to ~watch~ props changes to update ~cache~.

    When some cache vnode matched, move it out of ~cache~ and ~keys~.

    If it is not actived, call ~vnode.$destory~ to delete it.
