#+STARTUP: all
#+CREATED: [2021-09-26 19:13]
* video
** Refers
   - https://juejin.cn/post/6844903886914846728
   - https://www.bbc.co.uk/rd/blog/2016-01-h264-h265-avc-advanced-video-coding-hevc-high-efficiency
   - https://www.infoq.cn/article/uiPl8dIuQmhipKb3q3Tz
   - http://docs.monibuca.com/
** 纵览
   视频文件分后缀和编码.

   后缀可以说明它匹配的是哪个容器., 编码标准决定浏览器和系统是否支持. 

   通常来说, web 视频格式一般都是使用 mp4 容器, H264 标准编码. 
** 视频(容器)格式
*** AVI Audio Video Interactive
    微软, 最长寿, 只有一个视频和音频轨道, 不提供控制功能
*** WMV Windows Media Video
    微软, ASF Advanced Systems Format 封装, 数字版权保护功能. 
*** MPEG Moving Picture Experts Group
    控制功能丰富, 可以用多个视频.

    mpg/mpeg/mp4/3gp/3g2
*** Matroska
    mkv,  可以把不同编码和不同音频, 字幕封装到一起. 交互可控强大. 
*** Real Video Real Media
    RM, 可变比特率的 RMVB.

    制作简单, 压缩比率和编码没有比 H264 强. 
*** QuickTime File Format
    苹果, MPEG-4 标准的基础, 内容丰富, 视频音频图片文字, mov/qt
*** OggMedia
    支持多轨道的, 开放的多媒体系统项目. 
    
    ogg/ogv/ogaMOD
** 渐进式视频
*** H264/AVC
    一般编码格式, m4v 容器也是这个编码. 这是 Apple 为具有 DRM 保护的 H264 视频开发的 mp4 衍生品.

    兼容性最好, 基本所有浏览器和移动端都支持.

    也极狐所有 pc 和移动端设备都支持 H264 硬件编码加速, 编码解码速度很快. 

    使用简单, 插入链接即可.

    网速和延迟会影响视觉质量, 高峰期或者移动网络观影体验会不好. 
*** H265/HEVC
    容器相同, 编码不同, 压缩效率极高的视频格式. 体积减少 50%.

    问题:
    - 仅限于 Apple 设备, 只有 Safari 和 iOS 可用
    - 高版权税收
    - 因为压缩复杂, 编码速度慢, 生成视频慢.
    - 模糊
*** VP9
    谷歌开源, 谷歌使用 webm 容器, mkv 容器. VP9 编码可以用 webm. 

    编码有 VP8 和 VP9, 体积小, 编码慢, 类似 H265.

    webm 仅 Chrome 和 Android 支持. 
*** AV1
*** VVC
** 自适应比特率 ABR
   视频被分为块, HTTP 媒体流通信协议, 不同分辨率不同比特率可以切换. 
*** HLS
    iOS 外, 可以通过 videojs 的 viewer 支持.

    可以通过视频内容不同, 选择不同的 比特率. 可以使用 per-title encoding.  
*** MPEG-DASH
** 流媒体服务器
*** 1.0
    FCS, Flash Communication Server

    播放和推流都是由 FlashPlayer 承担
    FlashPlayer 和 FMS 之间通过 RTMP 协议进行通讯

    RTMP 可以传输一些 action script 命令, 包括 RPC, 共享对象等, 沿用至今. 
*** 1.5
    FCS 授权费用高
    
    新生服务器:
    - Red5 Java
    - rtmpd crtmpserver C++ https://github.com/langhuihui/csharprtmp
*** 2.0
    Flash 被封杀, 前技术下岗, 新技术百花齐放
**** obs 推流
     obs 录制编码, ffmpeg 格式编码, 再与流媒体服务器沟通.

     协议:
     - RTSP WebRTC
     - RTMP
**** 拉流
***** FFplay, VLC 拉取 RTMP RTSP
***** HLS.js, video.js 拉取 HLS, DASH
***** Flv. js, Jessibuca
     基于 websocket, wasm 解码后通过 webgl 渲染到 canvas
**** go 相关服务新型服务器
     livego, gortmp
*** 3.0
    Monibuca go
** 其他
*** 帧
    视频动画中的最小单位, 一张图片. 
*** 帧速率
    fps 帧数 (FramesPer Second).

    市面上常见的手机录制帧速率大多为 30fps，电视 25/30(常用), 50/60fps 等(运动镜头)，高速摄影机 120/240fps(慢镜头)
*** 分辨率
    电视厂家: 4k 或者 8k. 列表:
    - SD 640 x 480
    - HD 1280 x 720
    - FHD 1960 x 1080
    - 4k 3820 x 2160
*** PAL & NTSC
    - NTSC 正交平衡调幅制度. 美国, 墨西哥, 日本, 台湾, 加拿大等
    - PAL 倒相正交平衡调幅. 新加坡、中国大陆及香港，澳大利亚、新西兰等.
      - 克服了 NTSC 制相位敏感, 色彩失真的缺点
    - SECAM 顺序传送彩色信号与存储恢复彩色信号制, 法国、东欧和中东一带
      - 采用时间分隔法来传送两个色差信号
*** 码流, 码率, Data Rate
    单位时间内使用的数据流量

    同分辨率, 视频码率越大, 压缩比越小, 画面质量越好.

    码流越大, 说明单位时间内取样率越大, 数据流, 精度就越高, 处理出来的文件就越接近原始文件, 图像质量越好, 画质越清晰, 要求播放设备的解码能力也越高.
*** 比特率, Bite rate
    和 码率 类似. 比特率越高, 传送的数据越大, 还原后的音质, 画质就越好. 

    分成:
    - VBR 动态比特率, 根据视频大小
    - ABR 平均比特率, 对低频使用低, 对高频大动态时使用高流量. 每 50 帧为一段
    - CBR 常数比特率, 最大. 
