#+STARTUP: all
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: advanced-mathematics
#+DATE: [2022-08-09 09:23]
* Refers
* pre
** base
- multiply multiplication 乘
- minus 减
- plus
- divide
- negative 负
- tan sin/cos
- sine
- cosine
  - oscillation 振动
  - growing motion, opponent
- radius 弧度
  - circumference of angle when 1 as radius 半径
- angles 角度
** algebra 代数
引用字母
** Fraction
A fraction having an integer as a numerator and an integer as a denominator. （分数：一个有整数分子和整数分母的分数。）
** Factorial 阶乘
$n! = nfactorial  = (n)(n...1)(1)$
** Binomial Theorem 二项式定理
** func type
- Cubic 三次
- Quadratic 二次
- Linear 一次, 线性
- Constant 常数

* Trigonometric functions 三角函数

$\sin\alpha = \frac{2\tan{\frac{\alpha}{2}}} {1 + \tan^2{\frac{\alpha}{2}} }$

$\cos\alpha = \frac{1 - \tan^2{\frac{\alpha}{2}}} {1 + \tan^2{\frac{\alpha}{2}}}$

$\tan\alpha = \frac{2\tan{\frac{\alpha}{2}}} {1 - \tan^2{\frac{\alpha}{2}} }$

* Calculus 微积分
** derivative 导数
Like relation between two function, distance and speed.

Find func1 from func2, two curves same infomation.

slope in axis

D for delta

pronounce dy dx: $dx/dy$,  can be wrote as y'

$\lim_{\Delta x \rightarrow 0}$

delta means changes $\Delta$

*** example
$y = x^n$ $\frac{dy}{dx} = nx^{n-1}$

$y = \sin x$ $\frac{dy}{dx} = \cos x$ $y'' = -\sin x$

$y = e^x$ $\frac{dy}{dx} = e^x$

*** purpose
Location the maximum and the minimum, tells goes up or down.

Key value we should look for at the first time we meet the graph.

Maybe local maximum.

** chain rule
$\frac{dy}{dx}=\frac{dy}{du} \frac{du}{dx}$
** the derivative of derivative 二阶导数
*** purpose
Tells the bending (弯曲度和方向) of the graph.

Bending up, bending down

Inflection point(拐点), $y'' = 0$

Acceleration to speed $\frac{d^2f}{dt^2}$

Set derivative to zero, find the answer
** exponential 指数函数

自然常数 e Euler

E, exponent, 表示以 10 为底的指数, 自然对数的底 $\exp$

E xponential series 指数级数: 第二重要的无穷级数

$e^x=y(x)=1+x+\frac{1}{2}x^2...+\frac{x^n}{n(n-1)...1}$

geometric series 几何指数

$y(x)=1+x+x^2...+x^n$

$e^{\ln x}=x$

5 个基本常数, $e^{\pi i} + 1 = 0$

i 为虚数单位
** integral 积分

导数的原函数 $y(x)=\int s(x)dx$

integral $\int$, $sum(\Delta y)$ when delta x goes to 0 (limit for caculus)

distance is the integral of speed
** limit
approach A,  close to A

Danger cases:
1. $\infty - \infty$
2. $0 * \infty$
3. $\frac{0}{0}$
   1. $\frac{\infty}{\infty}$
4. ${a_n}^{b_n}$ unstable
   - $(1+\frac{1}{n})^n=e$ 
   - $(1+\frac{1}{n^2})^n=1$ 
*** L'Hospital's Rule 洛必达法则
for $\frac{0}{0}$ and $\frac{\infty}{\infty}$

$\lim_{x\to{a}}\frac{f(x)}{g(x)}=\lim_{x\to{a}}\frac{f'(x)}{g'(x)}$

Only if the slope of secant to origin and origin line equals, $u(x) = u'(x)$

Slops equals When overlap or parallel.

The limit secant (割线) is tangent (切线)

- $\frac{0}{0}$, secant and origin line overlap
- $\frac{\infty}{\infty}$, secant and origin line parallel

*** continuous 连续性
For continuous func, for any $\epsilon$, $\delta$ exists.

$|x - a| < \delta$, $|f(x) - f(a)| < \epsilon$

** inverse function
$x=f^{-1}(y)$
