#+STARTUP: all
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: advanced-mathematics
#+DATE: [2022-08-09 09:23]
* Refers
* pre
** multiply multiplication 乘
** Fraction
A fraction having an integer as a numerator and an integer as a denominator. （分数：一个有整数分子和整数分母的分数。）
** Factorial 阶乘
$n! = nfactorial  = (n)(n...1)(1)$
** Binomial Theorem 二项式定理
** func type
- Cubic 三次
- Quadratic 二次
- Linear 一次, 线性
- Constant 常数

* Trigonometric functions 三角函数

$\sin\alpha = \frac{2\tan{\frac{\alpha}{2}}} {1 + \tan^2{\frac{\alpha}{2}} }$

$\cos\alpha = \frac{1 - \tan^2{\frac{\alpha}{2}}} {1 + \tan^2{\frac{\alpha}{2}}}$

$\tan\alpha = \frac{2\tan{\frac{\alpha}{2}}} {1 - \tan^2{\frac{\alpha}{2}} }$

* Calculus 微积分
** derivative 导数
Like relation between two function, distance and speed.

Find func1 from func2, two curves same infomation.

slope in axis

pronounce dy dx: $dx/dy$,  can be wrote as y'

$\lim_{\Delta x \rightarrow 0}$

delta means changes $\Delta$

*** example
$y = x^n$ $\frac{dy}{dx} = nx^{n-1}$

$y = \sin x$ $\frac{dy}{dx} = \cos x$ $y'' = -\sin x$

$y = e^x$ $\frac{dy}{dx} = e^x$

*** purpose
Location the maximum and the minimum, tells goes up or down.

Key value we should look for at the first time we meet the graph.

Maybe local maximum.

** chain rule
$\frac{dy}{dx}=\frac{dy}{du} \frac{du}{dx}$
** the derivative of derivative 二阶导数
*** purpose
Tells the bending (弯曲度和方向) of the graph.

Bending up, bending down

Inflection point(拐点), $y'' = 0$

Acceleration to speed $\frac{d^2f}{dt^2}$

Set derivative to zero, find the answer
** exponential 指数函数

自然常数 e Euler

E, exponent, 表示以 10 为底的指数, 自然对数的底 $\exp$

E xponential series 指数级数: 第二重要的无穷级数

$e^x=y(x)=1+x+\frac{1}{2}x^2...+\frac{x^n}{n(n-1)....1}}$

geometric series 几何指数

$y(x)=1+x+x^2...+x^n$

$e^{\ln x}=x$

5 个基本常数, $e^{\pi i} + 1 = 0$

i 为虚数单位
** integral
$$
