#+STARTUP: all
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: linear-algebra
#+DATE: [2021-01-06 21:59]
* Referrs
  - https://pabloinsente.github.io/intro-linear-algebra
  - https://hefferon.net/linearalgebra/
  - https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra
* translation
- pivot 主元
  - pivot column 主列
- elimination 消元
- P permutaion 置换矩阵
- U upper triangular 上三角矩阵, 上非 0
- L lower triangular 下三角矩阵
- diagonal 对角三角阵, 上下都是 0
- I identity matrix 单位阵
- Augmented matrix 增广矩阵
- linear conbination 
- vector 向量
- scaler 标量
- determinant 行列式
- T transpose 转置
- S symmetric 对称阵
- Factorization 分解
- rank 秩
- solution 解
- basis 基
* Ax = b linear conbination
* matrix elimination
Pivot can't be zero.
Exchange rows to make sure that not happen.
Use pivot to clean to column.

permutaion: matrix to exchange rows or columns.

Left multiply, get row exchange opertaion.
Right get column.

Order counts, combination still follow same order.
* matrix
Find independent columns

Rank: number of independent columns

Basis: all independent columns

origin matrix = Basis x R

column rank = row rank 
* multiply
$A_{mn}•B_{np}=C_{mp}$

$C_{MN}=\sum_{k=1}^n(A_{Mk}•B_{Np})$
* Inverse Matrix
$A•A^{-1}=I=A^{-1}•A$
** When inverse not exist
1. Take determinant and get zero
2. Find a vector x, with $Ax=0$
   1. $AA^{-1}x=0$, $x\neq{0}$
** Gauss-Jordan idea
1. A augment I
2. Downside elimination
3. Upside elimination
4. Get I augment with $A^{-1}$
* A=LU
$EA=U$

$A=LU$

Get inverse of E,
if no row exchange, multipiers go directly to L
* Elimination times
If first line change, $n^2+(n-1)^2\dots{1^2}$ times operation

Integral $1/3n^3$
* 2.7
* Permutaion
Execute row exchanges, n! counts
$A^{-1}A=I$

$(A^{-1})^{T}A^T=I$

- $PA=LU$
  - $P^{-1}=P^T$
  - $P^TP=I$
- $P^TP=S$
  - $(R^TR)^T=R^TR^{TT}=R^TR$
* Vector Spaces
$R^2$ all 2-dimension real vector

Every vector spaces need 0, because has to be allowed to muliply by 0.

Subspace rules:
- Addition, multiples still in space, no extending

All subspaces in $R^2$:
- All $R^2$
- All lines though origin
- origin

$R^n$ the same, with $R^{n-1}$ though origin
** Column Space
A = 3X2 matrix

All linear conbination of A, called $C(A)$ column space, form a subspace

Conbine subspace, get a plane, 3 - 1 dimension space. ($n\rightarrow{1}$)

Linear combination work, Ax = b
*** Check solution existed
Ax = 0, x in a subspace not zero

Av = 0, Aw = 0, A(v + w) = 0

if 0 is not the solution, no space existed
*** Elimination
When column all zero, means column is depdent on others

Rank: counts of pivots

- Pivot column
- Free column, assgin free variable
*** Solution
Rank tells number of solution

- Solubility: zero row equation
- Particular solution, free variable as zero
- Complete solution, add up solution of special solution of zero
  - Solution for $Ax=b$, special solution of $Ax=0$ with free variable

Condition:
- r = m = n
  - R = I
  - 1 solution
- r = n < m
  - $R=\begin{bmatrix} I \\ 0 \end{bmatrix}$
  - 0 or 1 solution
- r = m < n
  - $R=\begin{bmatrix} I & F \end{bmatrix}$
  - infinite solution
- r < n, r < m
  - $R=\begin{bmatrix} I & F \\ 0 & 0 \end{bmatrix}$
  - 0 or infinte
* independent
Any vector conbination except zero, summary is zero, means dependent.

For matrix, Ac = null space:
- Independent: c only , rank = column n
- Dependent: c is not zero, rank < n, free variable

Dimension of null space N(A) = n - r
** Basis
1. Independent
2. Span the space
** Span

Span the space with all linear conbination of vectors.

The column of matric span the column space.

Independent vector span the space.

Number of space basis vector is dimension.

Rank of *matrix* = dimension of *column space*
* 4 fundamental subspace
for A as m * n matrix

Null space means special solution y, make $yA = 0$

1. Column space C(A)
2. Null space N(A)
3. Row space $C(A^T)$
4. Left null space $N(A^T)$
   1. $A^Ty = 0$ -> $y^TA=0$, $y^T$ is on the left of A
   

Column space and row space has same dimension equals rank r.

Null space use free variables, others use pivot.

Null space, n - r dimension

Left null space, m - r dimension

Row exchange wont change row space, but change column space

Best basis, as clean as possible, example  0 1 1 0.

When in same basis and row space, they can transform to each other.
** Find left null space
$A^Ty = 0$ -> $y^TA=0$, $y^T$ is on the left of A

Left null space support to be y, with the spacial solution

1. Use identity matrix to permutaion, [AI]=>[RE]
2. Make R as clean as possible, find the rank(identity matrix), free matrix and zero.
3. EA = R, get the zero row
4. $(E_{m3})^T$ as y

$E_{MN}$ gets a sub space, rank($E_{MN}$) = m - r = counts of free variable
* subspaces
For 3 x 3 matrix space

$dim(S) + dim(U) = dim(S\cup{U}) + dim(S+U)$

A conbination of rank(N) counts rank 1 matrix can build a rank(N) martix
