#+STARTUP: all
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: linear-algebra
#+DATE: [2021-01-06 21:59]
* 
* Referrs
  - https://pabloinsente.github.io/intro-linear-algebra
  - https://hefferon.net/linearalgebra/
* translation
- pivot 主元
  - pivot column 主列
- elimination 消元
- P permutaion 置换矩阵
- U upper triangular 上三角矩阵, 上非 0
- L lower triangular 下三角矩阵
- diagonal 对角三角阵, 上下都是 0
- I identity matrix 单位阵
- Augment 增广矩阵
- linear conbination 
- vector 向量
- scaler 标量
- determinant 行列式
- T transpose 转置
- S symmetric 对称阵
- Factorization 分解
- rank 秩
* Ax = b linear conbination
* matrix elimination
Pivot can't be zero.
Exchange rows to make sure that not happen.
Use pivot to clean to column.

permutaion: matrix to exchange rows or columns.

Left multiply, get row exchange opertaion.
Right get column.

Order counts, combination still follow same order.
* matrix
Find independent columns

Rank: number of independent columns

Basis: all independent columns

origin matrix = Basis x R

column rank = row rank 
* multiply
$A_{mn}•B_{np}=C_{mp}$

$C_{MN}=\sum_{k=1}^n(A_{Mk}•B_{Np})$
* Inverse Matrix
$A•A^{-1}=I=A^{-1}•A$
** When inverse not exist
1. Take determinant and get zero
2. Find a vector x, with $Ax=0$
   1. $AA^{-1}x=0$, $x\neq{0}$
** Gauss-Jordan idea
1. A augment I
2. Downside elimination
3. Upside elimination
4. Get I augment with $A^{-1}$
* A=LU
$EA=U$

$A=LU$

Get inverse of E,
if no row exchange, multipiers go directly to L
* Elimination times
If first line change, $n^2+(n-1)^2\dots{1^2}$ times operation

Integral $1/3n^3$
* 2.7
* Permutaion
Execute row exchanges, n! counts
$A^{-1}A=I$

$(A^{-1})^{T}A^T=I$

- $PA=LU$
  - $P^{-1}=P^T$
  - $P^TP=I$
- $P^TP=S$
  - $(R^TR)^T=R^TR^{TT}=R^TR$
* Vector Spaces
$R^2$ all 2-dimension real vector

Every vector spaces need 0, because has to be allowed to muliply by 0.

Subspace rules:
- Addition, multiples still in space, no extending

All subspaces in $R^2$:
- All $R^2$
- All lines though origin
- origin

$R^n$ the same, with $R^{n-1}$ though origin
** Column Space
A = 3X2 matrix

All linear conbination of A, called $C(A)$ column space, form a subspace

Conbine subspace, get a plane, 3 - 1 dimension space. ($n\rightarrow{1}$)

Linear combination work, Ax = b
*** Check solution existed
Ax = 0, x in a subspace not zero

Av = 0, Aw = 0, A(v + w) = 0

if 0 is not the solution, no space existed
*** Elimination
When column all zero, means column is depdent on others

Rank: counts of pivots

- Pivot column
- Free column, assgin free variable
