#+STARTUP: all
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: autonomous-driving
#+DATE: [2022-07-29 10:44]
* Refers
* sensor device
** Lidar, Light Detection and Ranging, 激光雷达

1970 美国军方和 NASA 发明, 昂贵.

通常最高可达每秒 150000 次脉冲.

加大功率，而且对人体也有伤害. 
** Radar, Radio Detection and Ranging, 毫米波雷达, 无线电波

1940 美国海军发明. 
** 对比
Lidar 更清晰, 但容易受天气环境影响成像, 距离短. 
Radar 对环境兼容性更好, 距离中长, 容易被杂波噪音影响精度低.

Tesla 特斯拉 是唯一没有采用 LiDAR 传感器的知名自动驾驶汽车制造商. 
Tesla 的自动驾驶汽车采用 RADAR 技术作为主要传感器.

马斯克认为从第一性原理觉得, 人没有激光雷达, 靠眼睛, 鼻子, 耳朵, 车配置足够了.
后续会演变成纯视觉(2022 已更新系统, 就算装有 Radar 也不会使用, 纯摄像头). 
** IMU, IMU inertial motion unit 惯性运动单元 传感器
* Mode
** LCC, Lane Centering Control, 车道居中辅助
** ACC, Adaptive Cruise Control, 自适应巡航
** NGP, Navigation Guided Pilot
** APA, Auto Parking Assist System, 自动泊车系统
* Company
** Tesla
马斯克对纯视觉路线有非常系统和深度的思考, 并且一直坚持初心和实践.

通过频繁的对外技术分享一点一点释放出来, 一是树立技术品牌, 更多的是有意识地牵引整个行业朝着自己技术方向走. 
*** Strategy
**** 1. 九头蛇统一网络架构
Hydranet 九头蛇 感知神经网络架构:
- Backbone
- Neck
- Head

Backbone 和 Neck 作为主干, 进行特征提取, 而 Head 再根据任务的具体类型, 给出输出. 

通过 Head 种类的数量(超过 1000 个), 拉开同行差距. 
**** 2. BEV 干掉激光雷达和毫米波雷达
通过 不同传感器信息融合创建以自车为中心的坐标系 Vehicle Coordinate System，VCS.
即鸟瞰视角 BEV Birds Eye View.

通过摄像头融合视觉呈现 3D, 不需要接触雷达. 
**** 3. 时空序列干掉高精地图
时空序列特征层, 通过视频片段代替静态图层, 让感知网络具有短期记忆能力.

历史局部地图读写和实时构建, 导致视野盲区也可以使用. 
**** 4. 光子照相机干掉 ISP
图像信号处理器 ISP Image Signal Processing 是摄像头的处理部分.
将 CMOS 传感器获取到的原始图像, 进行白平衡、动态范围调整、滤波等操作, 以获得更高质量的图像, 给人看或者给机器看.

光子照相机 Photon to Control 直接将现实数据传递给神经网络, 减少多余处理和损耗
