#+STARTUP: content
* be-a-leader
** Refers
   - https://mp.weixin.qq.com/s/U-hqectN-fes7Td6Osut7Q
** 核心要点

   - 招聘
   - 目标
   - 沟通
   - 工程师文化
   - ask yourself

** 招聘

   宁缺勿滥。
   错误的人会耗费成倍的管理成本，也会对整个团队造成负面影响，需要其他人补位争吵。
   
   能力要求：
   - coding 能力
   - 对技术的热情
   - 能简明扼要地沟通
   - 积极乐观
   - 对团队目标的认同

   长期招聘，挖人。保持沟通，了解工作状态，不断建立信任，有计划优先考虑。

   候选人考虑机会的时候应该考量 TL。
   TL 必须为技术发声，开源，技术分享，技术文章等，感受到个人技术能力，技术思考和个人特质。
   
** 目标

   定义团队目标
   
   制定明确稳定的目标，凝聚团队精力和努力方向。
   
   - 与用户客户沟通，确定工作解决的问题和目标修改
   - 确定依赖和依赖和协作方，控制能力范围和参与者
   - 确定目标有一定技术竞争力，帮助团队长期发展，吸引人才

   接下来就是沟通，不怕罗嗦，细化目标，给每个同学对接深入的方向和承担的责任。
   保证目标和架构足够清晰，能力细化，追求深度而非广度。

** 沟通

   立即响应，建立信任。不然的话下次找你就是提转岗离职了。
   两周或至少一个月一次 1-on-1 关注沟通，记录每次进度保持员工关注。
   同步的进展可以在下次的时候对，提高信任感。

   主要问题围绕：
   - 近况，项目进展
   - 难点，是否需要帮助，是哪里有问题，有没有更好的技术方案还是只是做简单的 hack
   - 上次的 todo 进展 review
   - 记录心情

** 工程师文化

   团队文化的核心，吸引人才的关键。
   保证质量，鼓励 CR，UT，CI，知识分享。

   要做到以手艺为傲，真心把编程当成手艺来尊重。
   如果不是的话，大家都会把工作看成搬砖无异的事情，区别只是工资高低，人才构成必然是二流甚至三流。

   失去工程师文化的团队，会演变成看起来差不多 PPT 每天开会。
   技术人才流失，剩下的人继续用他们擅长的非技术技能生存。
