#+STARTUP: all
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: licence
#+DATE: [2022-07-11 11:42]
* Refers
* MIT
Massachusetts Institute of Technology, MIT, 又称 X11 协议

相对宽松的软件许可协议,这个协议唯一的条件就是在修改后的代码或者发行包包含原作者的许可信息

#+begin_quote
Copyright (C) <year> <copyright holders>

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#+end_quote

在软件和软件的所有副本中都必须包含以上著作权声明和本许可声明
* Apache
永久权利 一旦被授权，永久拥有.

全球范围的权利 在一个国家获得授权，适用于所有国家.假如你在美国，许可是从印度授权的，也没有问题.

授权免费 无版税， 前期、后期均无任何费用.

授权无排他性 任何人都可以获得授权

授权不可撤消 一旦获得授权，没有任何人可以取消.比如，你基于该产品代码开发了衍生产品，你不用担心会在某一天被禁止使用该代码
* BSD
BSD 是"Berkeley Software Distribution"的缩写，意思是"伯克利软件发行版"

#+begin_quote
 * Copyright (c) 1998, Regents of the University of California
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the University of California, Berkeley nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.}}
#+end_quote

BSD 代码鼓励代码共享, 但需要尊重代码作者的著作权.
BSD 由于允许使用者修改和重新发布代码, 也允许使用或在 BSD 代码上开发商业软件发布和销售, 因此是对商业集成很友好的协议.
而很多的公司企业在选用开源产品的时候都首选 BSD 协议, 因为可以完全控制这些第三方的代码, 在必要的时候可以修改或者二次开发.
* CC
Creative Commons 知识共享协议, 大多是被使用于设计类的工程上

1. 署名 作品上必须附有作品的归属.如此之后, 作品可以被修改, 分发, 复制和其它用途.
2. 相同方式共享 作品可以被修改. 分发或其它操作, 但所有的衍生品都要置于 CC 许可协议下.
3. 非商业用途 作品可以被修改. 分发等等, 但不能用于商业目的.但语言上对什么是"商业"的说明十分含糊不清 (没有提供精确的定义), 所以你可以在你的工程里对其进行说明.例如, 有些人简单的解释"非商业"为不能出售这个作品.而另外一些人认为你甚至不能在有广告的网站上使用它们. 还有些人认为"商业"仅仅指你用它获取利益.
4. 禁止衍生作品
* MPL Mozilla Public License
允许免费重发布, 免费修改, 但要求修改后的代码版权归软件的发起者

允许修改, 无偿使用

这种授权维护了商业软件的利益
* GPL GNU General Public License
GPL 的出发点是代码的开源/免费使用和引用/修改/衍生代码的开源/免费使用.
但不允许修改后和衍生的代码做为闭源的商业软件发布和销售. 
* LGPL
允许商业软件通过类库引用(link)方式使用 LGPL 类库而不需要开源商业软件的代码.
这使得采用 LGPL 协议的开源代码可以被商业软件作为类库引用并发布和销售.
GPL/LGPL 都保障原作者的知识产权, 避免有人利用开源代码复制并开发类似的产品. 
