#+STARTUP: all
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: hardware
#+DATE: [2022-11-11 13:46]
* Refers
* boot usb
1. Use balenaEtcher with iso, create a boot usb
2. ~F11~ change boot source order
* graphic cards
Nvidia provide linux and Windows Closed source drivers, but Mac don't.

So hackintosh can't use Nvidia over 1060, but AMD whick is open-source.
* nvidia smi
- GeForce RTX 40 series cards works with 525.xx, 520.xx NVIDIA drivers, (RTX 4090)
- GeForce RTX 30 series cards works with 525.xx, 520.xx, 515.xx, 510.xx and 470.xx NVIDIA drivers, (RTX 3090, RTX 3080 and RTX 3070, RTX 3060, RTX 3060 Ti)
- GeForce RTX 20 series cards works with 525.xx, 520.xx, 515.xx, 510.xx and 470.xx NVIDIA drivers (RTX 2080 Ti, RTX 2080, RTX 2070 Ti, RTX 2070, RTX 2060)
- GeForce GT/GTX 600/700/800/900/10 series cards works with 510.xx, 470.xx, and 390.xx NVIDIA drivers (GTX 1080 Ti, GTX 1080, GTX 1070, GTX 1060, GTX 1660 …)
- GeForce GT/GTX 400/500 series cards works with 390.xx NVIDIA drivers
- GeForce GT 8/9/200/300 series cards works with 340.xx NVIDIA drivers
* Monitor
** xrandr
Setup screen arrangement
* Motherboard
* Overview
#+begin_src bash
  # All hardware
  dmidecode
  neofetch

  # PCI connected
  lspci
#+end_src
* RAM
** ECC
* disk
** fdisk
Part settings
#+begin_src bash
  sudo fdisk /dev/sda
#+end_src
** lsblk
Preview all block devices
** parted
Change part size or label
** mount
Mount device to a path
#+begin_src bash
  sudo mount /dev/sda1 /mnt/somewhere
#+end_src
** cfdisk
Delete or change part type
** mkfs
Change fs type
#+begin_src bash
  sudo mkfs.ext4 /dev/sda
#+end_src
** /etc/fstab
Describe mount information
- Column 1: Device name.
- Column 2: Default mount point.
- Column 3: Filesystem type.
- Column 4: Mount options.
- Column 5: Dump options.
- Column 6: Filesystem check options.
** large size disk example
Delete all parts
#+begin_src bash
  sudo fdisk /dev/sda
#+end_src

Create parts
#+begin_src bash
  sudo parted /dev/sda
#+end_src

1. ~mklabel gpt~
2. ~unit TB~ , ~mkpart primary 0 7.3~
3. ~q~ 

Setup file system
#+begin_src bash
  mkfs.ext4 /dev/sda1
#+end_src

Mount
#+begin_src bash
  mkdir /data
  sudo mount /dev/sda1 /data

  # ignore right
  sudo mount -o fmask=000,dmask=000 /dev/sdXn /mnt/exfat
#+end_src
** io
Track
#+begin_src bash
  iotop
#+end_src
Test read, write
#+begin_src bash
  dd if=/dev/zero of=/mnt/disk/testfile bs=200M count=100 oflag=direct
  # 100+0 records in
  # 100+0 records out
  # 20971520000 bytes (21 GB, 20 GiB) copied, 82.7084 s, 254 MB/s
  dd if=/mnt/disk/testfile of=/dev/null  bs=200M count=100 iflag=direct
  # 100+0 records out
  # 20971520000 bytes (21 GB, 20 GiB) copied, 76.6379 s, 274 MB/s
#+end_src

