#+STARTUP: content
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: makefile
#+DATE: [2022-01-03 22:38]
* Refers
- https://seisman.github.io/how-to-write-makefile/overview.html
* 概述
自动化编译, 写好了 make 就可以执行

make 是用来解释 makefile 的工具, 不同 IDE 不同
** 编译
首先将源文件编译出中间代码, windows 下的  ~.obj~ , unix 下的  ~.o~ 

