#+STARTUP: content
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: 计算机内存
#+DATE: [2021-11-12 18:21]
* Refers
1.RAM（RamdomAccessMemory）：
　易挥发性随机存取存储器，高速存取，读写时间相等，且与地址无关，如计算机内存等。 

2.ROM（Read Only Memory）：
　　　　　　　　　　　　　　只读存储器。断电后信息不丢失，如计算机启动用的 BIOS 芯片。存取速度很低，（较 RAM 而言）且不能改写。
　　　　　　　　　　　　　　由于不能改写信息，不能升级，现已很少使用。
* RAM RamdomAccessMemory

* vmstat
In addition to CPU monitoring and I/O monitoring you can monitor your memory usage with vmstat


#+begin_src bash
  ~$ vmstat
  procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----

  r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st

  1  0      0 396528  38816 384036    0    0     4     2   38   79  0  0 99  0  0
#+end_src

The fields are as follows:

procs
- r - Number of processes for run time
- b - Number of processes in uninterruptible sleep
  
memory
- swpd - Amount of virtual memory used
- free - Amount of free memory
- buff - Amount of memory used as buffers
- cache - Amount of memory used as cache
  
swap
- si - Amount of memory swapped in from disk
- so - Amount of memory swapped out to disk
  
io
- bi - Amount of blocks received in from a block device
- bo - Amount of blocks sent out to a block device

system
- in - Number of interrupts per second
- cs - Number of context switches per second
  
cpu
- us - Time spent in user time
- sy - Time spent in kernel time
- id - Time spent idle
- wa - Time spent waiting for IO

* free
#+begin_src bash
  $ free -h
                total        used        free      shared  buff/cache   available
  Mem:           247G        128G        3.0G         56M        116G        121G
  Swap:            0B          0B          0B
#+end_src

- total	Total installed memory
- used	Memory currently in use by running processes (used= total – free – buff/cache)
- free	Unused memory (free= total – used – buff/cache)
- shared	Memory shared by multiple processes
- buffers	Memory reserved by the OS to allocate as buffers when process need them
- cached	Recently used files stored in RAM
- buff/cache	Buffers + Cache
- available	Estimation of how much memory is available for starting new applications, without swapping.
