#+STARTUP: all
#+SETUPFILE: ~/.emacs.d/org-styles/html/main.theme
#+TITLE: dns
#+DATE: [2022-01-24 10:31]
* Refers
- 所有类型 https://en.wikipedia.org/wiki/List_of_DNS_record_types
* DNS Domain Name System
name 域名 domain name, SLD + TLD
常规 url https://www.baidu.com, 其中:
- https protocol
- www Subdomain, CNAME 标记
- baidu SLD Second Level Domain, 顶级域名, 基础域名, 根域名
- com TLD
- . Subdirectory

一般 NS 记录会被存储在 顶级域名服务器上 (TLD Top Level Domain server).
一共有 1000 多个 TLD, 一个 com, 其他 gov domain. 
* DNS 查询路径
如果没返回则下一步:
1. 浏览器查询 ip 记录
2. 逐层询问解析器, 知道根服务器(ISP 互联网服务提供商)
3. 被告知域名所属 TLD 服务器
4. TLD 告知 权威域名服务 Authoritative nameserver 地址, 记录 NS 的所有 ip
* A 记录  IPv4 address record
单个域名指向单个 ip.

一般包括:
- name
- description
- ttl


examples:
#+begin_src bash
  google.com. 300 IN A 173.194.222.101
#+end_src

300 s, TTL Time-to-live.
* CNAME 记录, 别名记录 Canonical Name record
多个域名映射到另一个域名, 别名记录需要有 A 记录.
** 和地址记录区别
CNAME 稳定, 修改 IP 只需要修改别名的 A 记录即可, 不需要每个都改.

CNAME 访问必须要 www 别名前缀, A 记录可以不用. 
* AAAA 记录 IPv6 address record
类似 A 记录, IPv6
* TXT record
任意文字记录, 一般用于域名拥有校验
* NS Nameserver 域名记录
NS 记录域名指向 DNS 服务器, 存储各种域名记录信息.
examples:
#+begin_src bash
  ns1.arius.com
  ns2.arius.com
#+end_src
* MX Record Mail Exchanger Record
邮箱, 包括:
- name
- priority 越小越优先
- description
- ttl

#+begin_src bash
  google.com. 600 IN MX 10 alt1.aspmx.l.google.com.
  google.com. 600 IN MX 20 alt2.aspmx.l.google.com.
  google.com. 600 IN MX 30 alt3.aspmx.l.google.com.
#+end_src
